apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: shahidraza0098/argocd-fastapi:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
