apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi-kustomize
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shahidraza-telespazio/argocd-kustomize  # Replace with your repository URL
    targetRevision: HEAD  # Specify branch or tag, e.g., 'main'
    path: overlays/dev  # Path to the Kustomize overlay directory
  destination:
    server: https://kubernetes.default.svc
    namespace: app  # The target namespace for your application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
