apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 4
  template:
    spec:
      containers:
      - name: myapp
        image: shahidraza0098/argocd-fastapi:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
